force-app/main/default/objects/Retention_Rule__mdt/Retention_Rule__mdt.object-meta.xml
<CustomObject>
    <label>Retention Rule</label>
    <pluralLabel>Retention Rules</pluralLabel>
</CustomObject>

force-app/main/default/objects/Retention_Rule__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Retention_Rules</relationshipLabel>
    <relationshipName>Retention_Rules</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Retention_Rule__mdt/fields/WHERE_Clause__c.field-meta.xml
<CustomField>
    <fullName>WHERE_Clause__c</fullName>
    <label>WHERE Clause</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SFDeleterRuntime.cls
public inherited sharing class SFDeleterRuntime {

  static final Map<string, List<Retention_Rule__mdt>> RETENTIONRULES = new Map<string, List<Retention_Rule__mdt>>();

  static {
    // Grab all of the Autovalue settings, put into a Map<String, List<>> to provide easy access.
    List<Retention_Rule__mdt> avss = [
      SELECT
        Object__c,
       WHERE_Clause__c
      FROM Retention_Rule__mdt
      WITH USER_MODE
    ];

    for (Retention_Rule__mdt avs : avss) {
      // Populate the <Map,List<>>
      if (RETENTIONRULES.containsKey(avs.Object__c)) {
        RETENTIONRULES.get(avs.Object__c).add(avs);
      } else {
        RETENTIONRULES.put(
          avs.Object__c,
          new List<Retention_Rule__mdt>{ avs }
        );
      }
    }
  }







}